1222222

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -11,16 +11,19 @@ function get_ip(){
 function set_ip(){
 	netconf='/etc/network/interfaces'
 	dns='dns-nameservers 61.139.2.69'
-	grep -q "dhcp" ${netconf}
-	if [ $? == 0 ];then
-	sed -i 's/dhcp/static/' ${netconf}
 	get_ip
-	echo ${HOST_IP} >> ${netconf}
-	echo ${MASK} >> ${netconf}
-	echo ${GW} >> ${netconf}
-	echo ${dns} >> ${netconf}
+	if ( grep -q "iface eth0 inet dhcp" ${netconf} ) && ( ! grep -q "${HOST_IP}" ${netconf} )
+	then
+	sed -i 's/dhcp/static/' ${netconf}
+		echo ${HOST_IP} >> ${netconf}
+                echo ${MASK} >> ${netconf}
+                echo ${GW} >> ${netconf}
+                echo ${dns} >> ${netconf}
+	elif ( grep -q "iface eth0 inet dhcp" ${netconf} ) && ( grep -q "${HOST_IP}" ${netconf} )
+	then
+		echo "/etc/network/interface file error" && exit 44
 	else
-	echo "set ip error" && exit 44
+		echo "please check interface file"
 	fi
 }
 function set_hostname(){
@@ -30,19 +33,22 @@ function set_hostname(){
 	ip=`echo ${HOST_IP} | cut -d. -f4`
 	if [ -z $ip ];then
 	echo "error" && exit 44
-	else
+	elif grep -q "${HOST_IP}" ${hosts}
+	then
+		echo "exist hosts record"
+	else 
+		echo "${HOST_IP}	comp-$ip" >> ${hosts}
 	hostname "comp-$ip"
 	echo "comp-$ip" > ${h_name}
-	echo "${HOST_IP}	comp-$ip" >> ${hosts}
 	fi
 }
 
 function set_apt_sources(){
-filename='/etc/apt/sources.list.d/new.list'
-echo 'deb http://apt.puppetlabs.com precise main' > ${filename}
-echo 'deb-src http://apt.puppetlabs.com precise main' >> ${filename}
-echo 'deb http://apt.puppetlabs.com precise dependencies' >> ${filename}
-echo 'deb-src http://apt.puppetlabs.com precise dependencies' >> ${filename}
-echo 'deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-proposed/folsom main' >> ${filename}
-echo 'deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/folsom main' >> ${filename}
+	filename='/etc/apt/sources.list.d/new.list'
+	echo 'deb http://apt.puppetlabs.com precise main' > ${filename}
+	echo 'deb-src http://apt.puppetlabs.com precise main' >> ${filename}
+	echo 'deb http://apt.puppetlabs.com precise dependencies' >> ${filename}
+	echo 'deb-src http://apt.puppetlabs.com precise dependencies' >> ${filename}
+	echo 'deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-proposed/folsom main' >> ${filename}
+	echo 'deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/folsom main' >> ${filename}
 }
