2 commit

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,101 +1,52 @@
-# functions - Common functions used by DevStack components
+###############################################
+function get_ip(){
+	HOST_IP=`LC_ALL=C /sbin/ifconfig eth0 | grep -m 1 'inet addr:'| cut -d: -f2 | awk '{print $1}'`
+	MASK=`LC_ALL=C /sbin/ifconfig eth0 | grep -m 1 'inet addr:'| cut -d: -f4`
+	GW=`route -n | grep 'UG[ \t]' | awk '{print $2}'`
+#	echo ${HOST_IP}
+#	echo ${MASK}
+#	echo ${GW}
 
-# Save trace setting
-XTRACE=$(set +o | grep xtrace)
-set +o xtrace
-
-
-# apt-get wrapper to set arguments correctly
-# apt_get package [package ...]
-function apt_get() {
-    [[ "$OFFLINE" = "True" || -z "$@" ]] && return
-    local sudo="sudo"
-    [[ "$(id -u)" = "0" ]] && sudo="env"
-    $sudo DEBIAN_FRONTEND=noninteractive \
-        http_proxy=$http_proxy https_proxy=$https_proxy \
-        apt-get --option "Dpkg::Options::=--force-confold" --assume-yes "$@"
+}
+function set_ip(){
+	netconf='/etc/network/interfaces'
+	dns='dns-nameservers 61.139.2.69'
+	grep -q "dhcp" ${netconf}
+	if [ $? == 0 ];then
+	sed -i 's/dhcp/static/' ${netconf}
+	get_ip
+	echo ${HOST_IP} >> ${netconf}
+	echo ${MASK} >> ${netconf}
+	echo ${GW} >> ${netconf}
+	echo ${dns} >> ${netconf}
+	else
+	echo "set ip error" && exit 44
+	fi
+}
+function set_hostname(){
+	hosts='/etc/hosts'
+	h_name='/etc/hostname'
+	get_ip
+	ip=`echo ${HOST_IP} | cut -d. -f4`
+	if [ -z $ip ];then
+	echo "error" && exit 44
+	else
+	hostname "comp-$ip"
+	echo "comp-$ip" > ${h_name}
+	echo "${HOST_IP}	comp-$ip" >> ${hosts}
+	fi
 }
 
-
-# Gracefully cp only if source file/dir exists
-# cp_it source destination
-function cp_it {
-    if [ -e $1 ] || [ -d $1 ]; then
-        cp -pRL $1 $2
-    fi
+function set_apt_sources(){
+	file='/etc/apt/sources.list.d/new.list'
+(
+	cat <<EEE
+deb http://apt.puppetlabs.com precise main
+deb-src http://apt.puppetlabs.com precise main
+deb http://apt.puppetlabs.com precise dependencies
+deb-src http://apt.puppetlabs.com precise dependencies
+deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-proposed/folsom main
+deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/folsom main
+EEE 
+) > ${file}
 }
-
-
-# Prints "message" and exits
-# die "message"
-function die() {
-    local exitcode=$?
-    set +o xtrace
-    echo $@
-    exit $exitcode
-}
-
-
-# Checks an environment variable is not set or has length 0 OR if the
-# exit code is non-zero and prints "message" and exits
-# NOTE: env-var is the variable name without a '$'
-# die_if_not_set env-var "message"
-function die_if_not_set() {
-    (
-        local exitcode=$?
-        set +o xtrace
-        local evar=$1; shift
-        if ! is_set $evar || [ $exitcode != 0 ]; then
-            set +o xtrace
-            echo $@
-            exit -1
-        fi
-    )
-}
-
-
-# Grab a numbered field from python prettytable output
-# Fields are numbered starting with 1
-# Reverse syntax is supported: -1 is the last field, -2 is second to last, etc.
-# get_field field-number
-function get_field() {
-    while read data; do
-        if [ "$1" -lt 0 ]; then
-            field="(\$(NF$1))"
-        else
-            field="\$$(($1 + 1))"
-        fi
-        echo "$data" | awk -F'[ \t]*\\|[ \t]*' "{print $field}"
-    done
-}
-
-
-
-
-
-# Test if the named environment variable is set and not zero length
-# is_set env-var
-function is_set() {
-    local var=\$"$1"
-    if eval "[ -z $var ]"; then
-        return 1
-    fi
-    return 0
-}
-
-
-
-# Normalize config values to True or False
-# VAR=`trueorfalse default-value test-value`
-function trueorfalse() {
-    local default=$1
-    local testval=$2
-
-    [[ -z "$testval" ]] && { echo "$default"; return; }
-    [[ "0 no false False FALSE" =~ "$testval" ]] && { echo "False"; return; }
-    [[ "1 yes true True TRUE" =~ "$testval" ]] && { echo "True"; return; }
-    echo "$default"
-}
-
-# Restore xtrace
-$XTRACE
